name: Build and push release

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Raspberry Pi image
        run: |
          make build-pi 
      - name: Push to github
        run: |
          docker tag mcncnola/mcncnola ghcr.io/toots/mcncnola
          docker push ghcr.io/toots/mcncnola
